GoogleCloudDataproc/dataproc-spark-connect-python

google/cloud/dataproc_spark_connect/client/proxy.py
Since we bidirectionally copy between two sockets, when we hit an exception reading from one socket, we should close the other.
=> Close bridged sockets in the event of exceptions

google/cloud/dataproc_spark_connect/client/proxy.py, requirements.txt, setup.py, tests/unit/test_proxy.py
This change sets a timeout for accepted incoming socket connections in the tunnel-over-websocket proxy.
Without this, sockets inherit the default timeout of `None`, which causes them to be blocking but never time out.
=> Update proxy.py to set a timeout for incoming socket connections.

.gitignore, google/cloud/dataproc_spark_connect/session.py, tests/unit/test_session.py
The service now expects `/locations/` instead of `/regions/` in the path in calls agains the sessions API.
Note that there's a breakage in the upstream dependency of `google-cloud-dataproc`, so this needs to be patched to make tests pass locally. This still needs to be tested against the service.
=> Rename /regions/ path to /locations/ in client

tests/unit/test_proxy.py
On some OSes (in particular, macOS), `socket.accept()` results in a ConnectionAbortedError when the server socket is destroyed. We weren't catching this, so it was resulting in logspam and lots of warnings that obscured test results. This does not change the test bodies themselves (which were already passing).
=> test: fix proxy test warnings due to broken connections

google/cloud/spark_connect/session.py, tests/unit/test_session.py
Session terminations can be aborted if a session is still being created. Handling that case gracefully.
=> Changes to gracefully handle 409 from session terminations.

requirements-dev.txt, setup.py
This removes indirect transitive dependencies from the package and renames `requirements.txt` to `requirements-dev.txt` to reflect the fact that this is not actually used by the package itself but is only used for development.
=> chore: Clean up dependencies

requirements-dev.txt, setup.py
This pulls in the required versions of the pandas and pyarrow libraries.
=> fix: Switch pyspark dependency to pyspark[connect]

.dockerignore, cloudbuild/Dockerfile, cloudbuild/cloudbuild.yaml
This currently only runs unit tests, as integration tests will require some more environment plumbing. We seem to have introduced a regression in unit tests at some point, but that shouldn't block this.
=> ci: Create a test Dockerfile and run unit tests in cloud build

google/cloud/spark_connect/client/proxy.py
This change fixes a bug in the TCP-over-websocket proxy where  one end of the connection might not be closed when the other end is closed.
That, in turn, could cause messages in one direction to get dropped.
=> Fix a connection-closing bug in the TCP-over-websocket proxy.

google/cloud/spark_connect/client/proxy.py
1. Move the socket timeout setting to after the websocket connection is established, so that the client blocks until the end-to-end connection is done.
2. Increase that socket timeout from 1 second to 10 to reduce the likelyhood of prematurely timing out.
3. Extend the websocket open timeout from the default of 10 seconds to 30 seconds.
=> Fix timeouts for the proxy

google/cloud/spark_connect/client/proxy.py
This change updates the TCP-over-websocket proxy so that it only retries sending bytes a fixed number of times (up to 10) rather than retrying indefinitely.
This resolves an issue where the attempt to close the gRPC connection would sporadically hang indefinitely.
I was able to reproduce that issue locally by manually creating a session, getting the Spark Connect URL for that session, and then running the following code in a loop:
```py
import faulthandler
from google.cloud.spark_connect.client import DataprocChannelBuilder
from pyspark.sql.connect.session import SparkSession
faulthandler.enable()
faulthandler.dump_traceback_later(30)
connect_host = '...'
connect_url = f'sc://{connect_host}:443/;use_ssl=true'
channel_builder = DataprocChannelBuilder(connect_url)
spark = …
```
=> fix: Put a cap on the maximum number of retries for forwarding bytes.

.gitignore
This commit adds the `.vscode` directory to the `.gitignore` file. This prevents VS Code's settings and workspace files from being accidentally committed to the repository.
=> chore: Add VS Code to .gitignore

google/cloud/dataproc_spark_connect/session.py, tests/unit/test_session.py
This commit introduces the ability to configure the default datasource for Dataproc Spark Connect sessions using the `DATAPROC_SPARK_CONNECT_DEFAULT_DATASOURCE` environment variable.
When set to "bigquery", it automatically configures the session with optimized BigQuery settings, including write method, views enabled, and default catalog. This simplifies BigQuery integration and improves the user experience.
A warning message is logged if the environment variable is set to an unsupported value. Unit tests are added to verify the functionality.
=> feat: Add default datasource config via env var

google/cloud/dataproc_spark_connect/session.py, tests/unit/test_session.py
This change adds the `colab-notebook-id` label to the Dataproc Spark Connect session if the `COLAB_NOTEBOOK_ID` environment variable is set. This allows users to track sessions created from Colab notebooks.
=> feat: Add colab-notebook-id label to Dataproc Spark Connect session

google/cloud/dataproc_spark_connect/session.py
The `__apply_options` method was being called multiple times during session creation and retrieval, leading to potential inconsistencies and unnecessary operations. This commit removes the redundant calls to ensure options are applied only once during session initialization, streamlining the configuration process.
All integration tests passed. All unit tests passed except the timeout tests. No test updates needed.
=> Refactor: Remove redundant option application in DataprocSparkSession. The redundant config passing to spark session caused unwanted warning.

google/cloud/dataproc_spark_connect/session.py, tests/unit/test_session.py
This commit introduces validation for the Colab notebook ID before setting it as a label on Dataproc Spark Connect sessions. It ensures that the notebook ID complies with Google Cloud label value requirements (lowercase letters, numbers, and dashes only, starting and ending with alphanumeric characters). A warning message is logged if the ID is invalid, preventing the label from being set. This change prevents errors and ensures label consistency. Unit tests are added to validate the new validation function.
=> Fix: Validate Colab notebook ID for Dataproc session labels

tests/unit/test_session.py
This is a follow-up fix for PR #106.
=> fix: Fix unit tests providing needed mock dependencies

google/cloud/dataproc_spark_connect/session.py
This currently opens the link in the new tab and displays URL not found since the url in not a valid UI url, will add this change once the UI changes are done.
=> fix: Hide 'View Session Details' button from the output.

google/cloud/dataproc_spark_connect/session.py, tests/unit/test_session.py
This is needed to not print the redundant URL when no query gets executed on remote spark server. `SELECT` clause is a transformation evaluated lazily on an action.
**OLD**
**NEW**
=> fix: Update per-operation Spark UI URL print logic to skip SELECT clause

google/cloud/dataproc_spark_connect/session.py
Notebook:
Python shell:
IPython shell:
=> fix: Fix per-operation Spark UI link display logic

tests/unit/test_session.py
avoid loading the .env file to impact this unit test 
unit tests don't need values from env vars. env vars are for integration test only.
but accidently loading env vars impacted running this unit test
=> test: avoid local env impacting unit test

google/cloud/dataproc_spark_connect/session.py, tests/unit/test_session.py
The session name is not available immediately after session creation started, the code should wait until it become available
verifed: https://screencast.googleplex.com/cast/NTAxNDYzNTk0OTMyNjMzNnwxYmU5ZjliZC1iMQ
=> fix: pysparkvalue error
